drop table "SYSTEM"."CUSTOMERACCOUNT" cascade constraints PURGE;
drop type "SYSTEM"."CUSTOMERACCOUNTTYPE" force;
drop table "SYSTEM"."ACCOUNTTABLE" cascade constraints PURGE;
drop type "SYSTEM"."ACCOUNTTYPE" force;
drop table "SYSTEM"."EMPLOYEETABLE" cascade constraints PURGE;
drop type "SYSTEM"."EMPLOYEETYPE" force;
drop table "SYSTEM"."CUSTOMERTABLE" cascade constraints PURGE;
drop type "SYSTEM"."CUSTOMERTYPE" force;
drop table "SYSTEM"."BRANCHTABLE" cascade constraints PURGE;
drop type "SYSTEM"."BRANCHTYPE" force;
drop type "SYSTEM"."PHONENESTED" force;
drop type "SYSTEM"."PEOPLETYPE" force;
drop type "SYSTEM"."ADDRESSTYPE" force;
drop type "SYSTEM"."PHONETYPE" force;